-- =============================================================================
-- Generated by lightline to lualine theme converter
--   https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9
-- License: MIT License
-- =============================================================================

local colors = {
  color7   = "#6897bb",
  color2   = "#2b2b2b",
  color1   = "#323232",
  color4   = "#ffc66d",
  color11  = "#629755",
  color3   = "#a9b7c6",
  color0   = "#9876aa",
  color8   = "#ff6b68",
}

local darcula = {
  normal = {
    b = { fg = colors.color0, bg = colors.color1 },
    a = { fg = colors.color2, bg = colors.color0 , gui = "bold", },
    c = { fg = colors.color3, bg = colors.color1 },
  },
  visual = {
    b = { fg = colors.color4, bg = colors.color1 },
    a = { fg = colors.color2, bg = colors.color4 , gui = "bold", },
  },
  inactive = {
    b = { fg = colors.color7, bg = colors.color1 },
    a = { fg = colors.color2, bg = colors.color7 , gui = "bold", },
    c = { fg = colors.color3, bg = colors.color1 },
  },
  replace = {
    b = { fg = colors.color8, bg = colors.color1 },
    a = { fg = colors.color2, bg = colors.color8 , gui = "bold", },
  },
  insert = {
    b = { fg = colors.color11, bg = colors.color1 },
    a = { fg = colors.color2, bg = colors.color11 , gui = "bold", },
  },
}

return darcula