#!/usr/bin/env bash

if [[ -z $TMUX ]]; then
    echo "$(basename $0): not inside tmux session"
    exit 1
fi

split="v" # default split is vertical

while getopts "hv" option
do 
    case "${option}" in
        h)split="h";; # horizontal split
        v)split="v";; # vertical split
    esac
done

shift $(($OPTIND - 1))

if [[ $# -eq 1 ]]; then
    window_name=$1
else
    echo "Usage: $(basename $0) [-v] [-h] window_name"
    exit 1
fi

session_name=$(tmux display-message -p "#S")
target="$session_name:$window_name"

if tmux has-session -t $target 2> /dev/null; then
    tmux split-window -$split -t $target
fi
